"""
RevAudit Bot Filter Module
UCS503 Software Engineering Lab, TIET | Advisor: Dr. Sukhpal Singh
Team ArchCoders

Filters out automated bot-generated PRs (Dependabot, Renovate, Actions, Stale bots)
to prevent skewing human review effort and latency baselines.
"""

import re
from typing import Dict, List, Tuple, Any

# Bot regex patterns matching usernames and display names
BOT_USERNAME_PATTERNS = [
    r"\[bot\]$",
    r"^dependabot(-preview)?(\[bot\])?$",
    r"^renovate(-bot)?(\[bot\])?$",
    r"^github-actions(\[bot\])?$",
    r"^stale(\[bot\])?$",
    r"^codecov(-io)?(\[bot\])?$",
    r"^greenkeeper(\[bot\])?$",
    r"^snyk-bot(\[bot\])?$",
    r"^imgbot(\[bot\])?$",
    r"^allcontributors(\[bot\])?$",
    r"^mergify(\[bot\])?$",
    r"^semantic-release-bot$",
    r"^pyup-bot$",
    r"^pre-commit-ci(\[bot\])?$"
]

# Bot PR title patterns
BOT_TITLE_PATTERNS = [
    r"^bump\s+\S+\s+from\s+\S+\s+to\s+\S+",
    r"^chore\(deps(-dev)?\):",
    r"^fix\(deps(-dev)?\):",
    r"^build\(deps(-dev)?\):",
    r"^update\s+dependency\s+\S+\s+to\s+",
    r"^\[automated\]",
    r"auto-generated by"
]

_COMPILED_USER_REGEX = [re.compile(p, re.IGNORECASE) for p in BOT_USERNAME_PATTERNS]
_COMPILED_TITLE_REGEX = [re.compile(p, re.IGNORECASE) for p in BOT_TITLE_PATTERNS]


def is_bot_author(author: str, title: str = "") -> bool:
    """
    Checks if a PR was authored by an automated bot account or has an automated pattern.
    
    Args:
        author: The GitHub login or username string.
        title: Optional PR title to inspect for automated dependency bump signatures.
        
    Returns:
        True if the author or title matches a known bot pattern, False otherwise.
    """
    if not author:
        return False

    clean_author = author.strip().lower()

    # Check username patterns
    for regex in _COMPILED_USER_REGEX:
        if regex.search(clean_author):
            return True

    # Check title patterns if title is provided
    if title:
        clean_title = title.strip()
        for regex in _COMPILED_TITLE_REGEX:
            if regex.search(clean_title):
                return True

    return False


def filter_bot_prs(pr_records: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """
    Splits a collection of PR records into human-authored PRs and bot-authored PRs.
    
    Args:
        pr_records: List of PR dictionaries containing 'author', 'author_id', or 'user'.
        
    Returns:
        A tuple of (clean_human_prs, excluded_bot_prs).
    """
    human_prs = []
    bot_prs = []

    for pr in pr_records:
        author = pr.get("author") or pr.get("author_id") or pr.get("user", {}).get("login", "") if isinstance(pr.get("user"), dict) else str(pr.get("user", ""))
        title = pr.get("title", "")
        
        # Check if already tagged as bot in data
        if pr.get("is_bot_filtered") or pr.get("is_bot") or is_bot_author(author, title):
            pr_copy = dict(pr)
            pr_copy["is_bot_filtered"] = True
            bot_prs.append(pr_copy)
        else:
            pr_copy = dict(pr)
            pr_copy["is_bot_filtered"] = False
            human_prs.append(pr_copy)

    return human_prs, bot_prs


def calculate_bot_exclusion_stats(pr_records: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Computes summary metrics regarding bot filtering.
    """
    human_prs, bot_prs = filter_bot_prs(pr_records)
    total = len(pr_records)
    bot_count = len(bot_prs)
    human_count = len(human_prs)
    exclusion_pct = round((bot_count / total * 100.0), 2) if total > 0 else 0.0

    return {
        "total_prs_ingested": total,
        "clean_human_prs": human_count,
        "excluded_bot_prs": bot_count,
        "bot_exclusion_pct": exclusion_pct
    }
